[airflow]
dev_host = ""
dev_port = 5432
dev_user = "admin"
dev_password = "airflow"
dev_db = ""

prd_host = ""
prd_port = 5432
prd_user = "admin"
prd_password = "airflow"
prd_db = ""

[redshift]
dev_host = ""
dev_port = 5432
dev_user = "junhyeok"
dev_password = ""
dev_database = ""

prd_host = ""
prd_port = 5432
prd_user = "junhyeok"
prd_password = ""
prd_database = ""
